ekf_filter_node:
  ros__parameters:
    frequency: 10.0
    sensor_timeout: 0.1
    two_d_mode: false  # Set to true for ground robots (ignores Z and small tilts)
    publish_tf: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # --- LiDAR Odometry (Position) ---
    odom0: /odom_rf2o
    odom0_config: [true,  true,  false, # X, Y, Z (Position)
                   false, false, true, # Roll, Pitch, Yaw (Orientation)
                   true,  true,  false, # VX, VY, VZ (Velocity)
                   false, false, false, # vRoll, vPitch, vYaw
                   false, false, false] # Acceleration
    odom0_differential: false
    odom0_relative: false